apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfronteg
spec:
  selector:
    matchLabels:
      app: webfronteg
  template:
    metadata:
      labels:
        app: webfronteg
    spec:
      containers:
      - name: webfronteg
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sitedata
          mountPath: "/var/www/"
      volumes:
        - name: sitedata
          persistentVolumeClaim:
            claimName: pvc-webfronteg

---
apiVersion: v1
kind: Service
metadata:
  name: svc-webfronteg
spec:
  type: NodePort
  selector:
    app: webfronteg
  ports:
  - port: 80
    targetPort: 80
