apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: mysql-data
spec:
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
