apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: wordpress
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: master
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql
                key: user
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql
                key: db-name
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: db-user-pswd
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: db-root-pswd
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysql-data

---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
